export const ITEM_TYPE_RECENT   = 'recent'
export const ITEM_TYPE_FAVORITE = 'favorite'
export const ITEM_TYPE_SEARCH   = 'search'
export const SAVE_KEY_SEARCH_TEXT = 'searchText'
export const SAVE_KEY_LAST_ITEM_TYPE = 'lastItemType'
